### ISSUE TITLE
Can't install urllib3 1.18 with easy_install and setuptools 17.0 (py2.7)

### ISSUE THREAD

**Issue by marcinn** [shazow/urllib3#988] opened 2016-09-29 09:58 UTC
The following error occurs:

> error: Setup script exited with error in urllib3 setup command: Invalid environment marker: python_version <= "2.7"

Steps to reproduce:

* `virtualenv2 /tmp/env`
* `source /tmp/env/bin/activate`
* `easy_install setuptools==17.0`
* `easy_install urllib3==1.18`

I'm using [Buildout](http://www.buildout.org/en/latest/) which is using `easy_install` instead of `pip`, and build of my project is broken with urllib 1.18.

Additional notes:
* `pip` installs `urllib3==1.18` successfully.
* `easy_install` from `setuptools==18.0` installs `urllib3==1.18` successfully.
* `easy_install` from `setuptools==17.0` installs `urllib3==1.16` successfully.

I think that `urllib3` should require `setuptools>=18.0` or should work with `setuptools==17.0`.

**Comment by Lukasa** [comment] 2016-09-29 10:03
Thanks, this is a duplicate of #986, which was resolved in #987.

**Closed by Lukasa** 2016-09-29 10:03 UTC

**Comment by marcinn** [comment] 2016-09-29 10:04
Ok, thanks!
