### ISSUE TITLE
Keep-alive broken in 1.10.3 with chunked transfer-encoding

### ISSUE THREAD

**Issue by lmikkelsen** [shazow/urllib3#598] opened 2015-04-24 14:01 UTC
Per kennethreitz/requests#2568, starting in urllib3 1.10.3 an exception is thrown if a connection with chunked transfer-encoding is reused.

**Comment by sigmavirus24** [comment] 2015-04-24 14:06
Thanks @lmikkelsen

**Comment by ne0ark** [comment] 2015-04-24 17:09
Yeh I am also having same issue is there a solution for this?

**Comment by Lukasa** [comment] 2015-04-24 17:37
We're working on it. =) Keep an eye on this issue for more.

**Comment by ne0ark** [comment] 2015-04-24 19:32
It seems like this is broken in mechanize as well.

**Comment by untitaker** [comment] 2015-04-25 16:24
I get a similar exception with the following script, but the traceback is different:

    import requests

    s = requests.session()

    r = s.get('http://httpbin.org/stream/20')
    s.get('http://httpbin.org/stream/20')

Start of traceback ([full](https://gist.github.com/untitaker/5b3ff800951747701ebb)):

    Traceback (most recent call last):
      File "/home/untitaker/projects/requests/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
        httplib_response = conn.getresponse(buffering=True)
    TypeError: getresponse() got an unexpected keyword argument 'buffering'
     
    During handling of the above exception, another exception occurred:

Happening with Python 3.4.3

**Comment by Lukasa** [comment] 2015-04-25 16:25
Please don't print the start of the traceback, it's irrelevant. Print the *end* of it. =D

**Comment by Lukasa** [comment] 2015-04-25 16:25
To be clear @untitaker, your traceback is different because you've got Python 3 printing the chained exceptions. If the others users did, they'd show the same traceback as you.

**Comment by ne0ark** [comment] 2015-04-25 16:40
Here is my traceback:

https://gist.github.com/ne0ark/a451c13de9e6643a751e

**Comment by sigmavirus24** [comment] 2015-04-26 03:23
So using *just* urllib3, I'm having trouble reproducing this. The following is more-or-less what an adapter does in requests

```py
import urllib3

url = 'http://httpbin.org/stream/20'
http = urllib3.PoolManager()
conn = http.connection_from_url(url)
response = conn.urlopen(
    method='GET',
    url=url,
    headers={
        'Connection': 'keep-alive',
        'Accept-Encoding': 'gzip, compress',
    },
    preload_content=False,
    decode_content=False,
)
list(response.stream())
response = conn.urlopen(
    method='GET',
    url=url,
    headers={
        'Connection': 'keep-alive',
        'Accept-Encoding': 'gzip, compress',
    },
    preload_content=False,
    decode_content=False,
)
list(response.stream())
```

**Comment by t-8ch** [comment] 2015-04-26 04:38
53a1e6a is the culprit.

**Comment by sigmavirus24** [comment] 2015-04-26 04:53
@t-8ch do we really think closing the connection is the right thing to do here?

**Comment by t-8ch** [comment] 2015-04-26 05:09
@sigmavirus24 I don't think so. But somehow httplib has to be conviced, that we are done with this response.

**Comment by t-8ch** [comment] 2015-04-26 05:35
Doing
```
if self._original_response is not None:
    self._original_response.fp = None
self.release_conn()
```
fixes the bug but is missing testcoverage

**Comment by t-8ch** [comment] 2015-04-26 05:59
@sigmavirus24 It seems even weirder. Running your example from upthread shows me *three* requests on two sockets in wireshark.
The second request is duplicated and sent on two sockets. I assume the exception is caught somewhere.

Using `requests` gives me two requests on one socket (as expected, plus the exception).

**Comment by t-8ch** [comment] 2015-04-26 06:01
Yeah, ofc retries... So requests disables retries which explains the differences.

**Comment by t-8ch** [comment] 2015-04-26 09:23
Also:
testing against a local httpbin works. And reading the documentation for the `release_con` parameter to `ConnectionPool.__init__` we should *not* try to automatically return the connection back to the pool, if we set `preload_content` (which we do).

@lmikkelsen Did you rnu into this problem using httpbin?

**Comment by sigmavirus24** [comment] 2015-04-26 15:29
To be clear, you can reproduce this with:

```py
import urllib3

url = 'http://httpbin.org/stream/20'
http = urllib3.PoolManager(
    block=False,
    num_pools=10,
    maxsize=10,
    strict=True,
    retries=0,
)
conn = http.connection_from_url(url)
response = conn.urlopen(
    method='GET',
    url=url,
    headers={
        'Connection': 'keep-alive',
        'Accept-Encoding': 'gzip, compress',
    },
    preload_content=False,
    decode_content=False,
)
list(response.stream())
response = conn.urlopen(
    method='GET',
    url=url,
    headers={
        'Connection': 'keep-alive',
        'Accept-Encoding': 'gzip, compress',
    },
    preload_content=False,
    decode_content=False,
)
list(response.stream())
```

For some reason I thought we were using something like 5 for the retries value.

**Comment by sigmavirus24** [comment] 2015-04-26 15:34
I've been looking into @t-8ch's solutions and calling `self._original_response.close()` simply rids us of the socket's fileobject. It also looks like @t-8ch has some commits that add tests and a fix for this. I'll wait for him to shape those up into something he's willing to send as a PR.

**Closed** 2015-04-27 16:57 UTC
