### ISSUE TITLE
Error: ConnectionError: HTTPConnectionPool: Max retries exceeded with url

### ISSUE THREAD

**Issue by thinkerou** [shazow/urllib3#1111] opened 2017-02-07 03:05 UTC
I have the following code(part):

    class Test(threading.Thread):
        
        # other more codes

        def _send_request(self, url):
            s = requests.Session()
            s.keep_alive = False
            resp = None
            try:
                resp = s.get(urls)
                data = resp.json()
            except:
                if resp is not None:
                    resp.connection.close()
                print traceback.print_exc()
                return (False, "")
            if resp is not None:
                resp.connection.close()
            return (True, data)

        def _send_meta_check_request(self, pk):
            urls = "/check/meta?method=innerselect&pk=" + pk
            b, d = self._send_request(urls)
            if b == False:
                return False

When I run the function: _send_meta_check_request, it will have the following errors:

    WARNING: 2017-02-07 10:30:22 [check599_new_v2.py: _send_request: 163] Traceback (most recent call last):
      File "check599_new_v2.py", line 160, in _send_request
        resp = session.get(urls)
      File "/home/work/.jumbo/lib/python2.7/site-packages/requests/sessions.py", line 468, in get
        return self.request('GET', url, **kwargs)
      File "/home/work/.jumbo/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/work/.jumbo/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
        r = adapter.send(request, **kwargs)
      File "/home/work/.jumbo/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
        raise ConnectionError(e, request=request)
    ConnectionError: HTTPConnectionPool(host='...', port=80): Max retries exceeded with url: ... (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)

BTW, the url is OK when I use `curl -v url` it can run right.

python version: `2.7.3`

**Comment by Lukasa** [comment] 2017-02-07 08:22
Hi there! This error is caused by the remote peer forcibly closing the connection on us unexpectedly, usually instead of sending a response. I can't very helpfully tell you what to do differently without some kind of packet capture so I can see both the request and response.

I should also note that you aren't running a recent Requests build. Old versions of Requests are likely to have bugs, and you would need to upgrade in order to guarantee that this is not related to a bug that we have already fixed.

**Comment by Lukasa** [comment] 2017-02-07 08:28
Apropos of nothing, this is also not a urllib3 bug: it's a Requests issue. You'd need to open this issue on the appropriate repository.

**Closed by Lukasa** 2017-02-07 08:28 UTC

**Comment by haikuginger** [comment] 2017-02-07 08:59
As an extra note, I've seen servers configured to drop requests from Python user agents, so it might be worth setting an alternate User-Agent header.

**Comment by sigmavirus24** [comment] 2017-02-07 12:22
> As an extra note, I've seen servers configured to drop requests from Python user agents, so it might be worth setting an alternate User-Agent header.

I've found those typically drop just any *non-Web browser* UA
