### ISSUE TITLE
IP shouldn't be set as SNI

### ISSUE THREAD

**Issue by jichao-zhang** [shazow/urllib3#1298] opened 2017-12-20 07:01 UTC
## Summary
According to RFC 6066, https://tools.ietf.org/html/rfc6066#section-3,
Literal IPv4 and IPv6 addresses are not permitted in "HostName".

However, when I send requests like resp = s.get('https://192.168.1.140', verify=False), requests will put 192.168.1.140 in SNI.

## How to reproduce
* Use tcpdump to collect network packets. `sudo tcpdump -X -S -s 0 -i eth0 -w wireshark.log`
* Run below script:
```python
import certifi
import urllib3
ip = '140.211.11.105'
http = urllib3.PoolManager(cert_reqs = 'CERT_NONE', ca_certs = certifi.where())
r = http.request('GET', 'https://' + ip) 
print(r.data)
```
* Use WireShark  to open wireshark.log collected by tcpdump. You will saw IP in SNI (140.211.11.105 in below screenshot)
![sni_ip_address](https://user-images.githubusercontent.com/34702338/34195028-7de83c8e-e596-11e7-9e7f-e88735b3d98f.png)

**Comment by tiran** [comment] 2017-12-20 08:45
Duplicate of #1224

**Comment by haikuginger** [comment] 2018-01-09 21:10
Closing as dupe.

**Closed by haikuginger** 2018-01-09 21:10 UTC
