### ISSUE TITLE
When using urllib3 with gevent and checking if a socket is closed an exception is raised

### ISSUE THREAD

**Issue by thedrow** [shazow/urllib3#541] opened 2015-02-02 14:34 UTC
```
Traceback (most recent call last):
  File "***", line 285, in request
    return HTTPConnectionPool.request(self, method, url, fields, headers, **urlopen_kw)
  File "***/lib/python2.7/site-packages/urllib3/request.py", line 75, in request
    **urlopen_kw)
  File "***/lib/python2.7/site-packages/urllib3/request.py", line 88, in request_encode_url
    return self.urlopen(method, url, **urlopen_kw)
  File "***/lib/python2.7/site-packages/urllib3/connectionpool.py", line 536, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "***/lib/python2.7/site-packages/urllib3/connectionpool.py", line 294, in _get_conn
    if conn and is_connection_dropped(conn):
  File "***/lib/python2.7/site-packages/urllib3/util.py", line 490, in is_connection_dropped
    return select([sock], [], [], 0.0)[0]
  File "***/lib/python2.7/site-packages/gevent/select.py", line 67, in select
    raise error(*ex.args)
error: (9, 'Bad file descriptor')
```

This is because gevent raises ```gevent.select.error``` instead of ```socket.error```.
Is there a way to gracefully handle this?

**Comment by Lukasa** [comment] 2015-02-02 16:05
Isn't that a `gevent` bug? Shouldn't they be monkeypatching `socket.error`?

**Comment by ml31415** [comment] 2015-02-02 16:42
I agree, that gevent should probably also patch their select method to throw `socket.error`. Besides that, catching any `Exception` instead of only `socket.error` won't hurt. Whenever there is an error in https://github.com/shazow/urllib3/blob/master/urllib3/util/connection.py#L32, the socket is likely to be dead, whatever error it was.

**Comment by sigmavirus24** [comment] 2015-02-02 16:49
@ml31415 no we really should only be catching the exceptions that we are expecting and know how to handle. The ones that we don't expect are ones that indicate there's something that the user is doing that they shouldn't or that something horribly wrong has happened. In those cases, if we keep trying we're going to end up doing something horribly wrong instead of allowing the user feedback through so the user knows what's wrong and can help us diagnose it.

**Comment by ml31415** [comment] 2015-02-02 16:55
The user is surely not doing anything wrong, when using gevent with urllib3, as gevent is officially claimed as being supported. There is already a lot of boiler plate in this utility to handle special select implementations like AppEngine, OSX, whatever. In case a specific solution is desired, I don't see why gevent then shouldn't deserve it's own exception there.

**Comment by sigmavirus24** [comment] 2015-02-02 17:09
> I don't see why gevent then shouldn't deserve it's own exception there.

AppEngine is something trending towards "real" Python. OSX is only an exception in that the default openssl does some ill-considered things but otherwise just works. gevent is something we support but which we shouldn't have to put so much effort into supporting (Note, the amount of effort to support the other two platforms is minimal). gevent needs to fix itself essentially.

Besides that, the above are all well-known ways that things can fail. I was addressing the suggestion to catch `Exception` and be done with it, because that's perhaps the worst potential solution to this problem.

In case it's still not obvious to you, gevent should be doing something, isn't, and we shouldn't have to handle or work around gevent's negligence. Gevent should fix its bug.

**Comment by shazow** [comment] 2015-02-02 17:54
+1 to gevent fixing this (maybe they can inherit their error from socket.error?),
-1 to catching Exception,
+0.5 to catching a reasonably specific subclass that gevent also uses (which doesn't seem the case),
+0 to catching gevent.select.error exception if we can detect gevent reasonably. Maybe wrap our own socket error thing on import? Dunno.

**Comment by ml31415** [comment] 2015-02-02 18:40
See https://github.com/gevent/gevent/blob/master/gevent/select.py#L10 . The error thrown from gevent is actually plain `select.error` from stdlib. 
```python
import select as __select__
error = __select__.error
```
I'd say it's fair to throw that in case some call to select fails, so it should be caught here, too.

**Comment by Lukasa** [comment] 2015-02-02 18:53
Yeah, `select.error` looks to be the exception thrown by `select`. The question is, why is `select` throwing exceptions?

**Comment by Lukasa** [comment] 2015-02-02 19:02
EBADF can get caused by double-closing a file descriptor, I suppose that's possible.

**Comment by Lukasa** [comment] 2015-02-02 19:07
Did anything happen *before* this exception was hit? Did you close the connection yourself, for example? Or was another exception hit?

**Comment by sigmavirus24** [comment] 2015-02-02 21:30
> EBADF can get caused by double-closing a file descriptor, I suppose that's possible.

We're generally really good about managing this stuff. At least I've never seen this ever in years of normal urllib3/requests usage.

**Comment by thedrow** [comment] 2015-02-03 06:14
We have no idea how to create a reproducible test case out of what we have yet.
We don't touch the socket ourselves. We use urllib3 for making the requests and httplib2 for connection pooling. The code predates requests so it wasn't used.

**Comment by Lukasa** [comment] 2015-02-03 06:48
You use httplib2 for connection pooling?

**Comment by thedrow** [comment] 2015-02-03 07:48
Yes.

**Comment by Lukasa** [comment] 2015-02-03 10:33
How are you integrating the two libraries?

**Comment by Lukasa** [comment] 2015-02-03 10:33
Because urllib3 also does connection pooling...

**Comment by thedrow** [comment] 2015-02-03 13:19
The code is very old and not in the best shape. Sometimes we have to make do.

**Comment by sigmavirus24** [comment] 2015-02-03 14:50
Yeah, so I have no confidence that this is something a regular user of requests/urllib3 would encounter here. Without any understanding of how httplib2 is likely interfering with our otherwise fine connection handling, I'm certain there's a realistic case for us to handle here.

**Comment by Lukasa** [comment] 2015-02-03 15:00
Let's be clear about our thinking.

I suspect `httplib2` is closing our socket. I also suspect `urllib3` is closing the socket. Therefore, the socket gets double-closed, so when we pass it to select we get EINTR. We need a reproduction of this case that does not get tainted by `httplib2`.

There is no expectation that anyone will manage `urllib3`'s connections but `urllib3`. If you do, you are squarely in 'undefined behaviour' land.

**Comment by shazow** [comment] 2015-02-07 01:28
Closing for now.

If anyone can reproduce this with pure urllib3, let's explore it further. :)

**Closed by shazow** 2015-02-07 01:28 UTC
