### ISSUE TITLE
Need to update error handling for pyOpenSSL

### ISSUE THREAD

**Issue by sigmavirus24** [shazow/urllib3#556] opened 2015-02-28 17:32 UTC
If an `SSLError` comes from `pyOpenSSL`, we attempt to determine if it's an error due to request timeouts on python 2.6 being raised as `BaseSSLErrors` [here](https://github.com/shazow/urllib3/blob/29aa09bde9c42cc9a8d79aac47ee3d362b438cca/urllib3/connectionpool.py#L314). If the handshake ends unexpectedly under pyOpenSSL, then we get an `SSLError` that has a captured `SysCallError` which when you call `str(SSLError(msg, SysCallError(code, msg)))` you get

```py
TypeError: __str__ returned non-string (type SysCallError)
```

So we might want to update how we handle SSLErrors to accomodate pyOpenSSL. To be clear, I observed this on: python 2.7.9 with openssl 1.0.1l (from brew) and I was using requests to debug an issue with `https://apissl.cloudfactory.com`, e.g., `requests.get('https://apissl.cloudfactory.com')`

**Comment by shazow** [comment] 2015-02-28 18:40
Yea that whole process is voodoo. :/

Open to basically any kind of change. What do you have in mind?

**Comment by sigmavirus24** [comment] 2015-02-28 18:57
I don't know yet. =P

**Comment by shazow** [comment] 2015-02-28 18:58
Somedays I wonder if we should just fork out to golang. :P

**Comment by Lukasa** [comment] 2015-02-28 19:22
A note that pyOpenSSL is no longer required for SNI in Python 2.7.9. =) Obviously I don't think that removes it from the support matrix, but it's worth being aware of.

**Comment by sigmavirus24** [comment] 2015-02-28 19:27
Right. I was just trying to see if that would help with the problem the user was encountering with apissl.cloudfactory.com. Works just fine otherwise but it blows up here.

**Comment by fuag15** [comment] 2015-03-26 20:31
Blows up to other api's as well but I'm not at liberty to divulge a uri, would be very interested in a fix for this

**Comment by lorenzog** [comment] 2015-06-26 13:44
I had to fix this on a production server by editing `requests/packages/urllib3/connectionpool.py`. At line 315, before `if 'timed out' in str(err) or 'did not complete (read)' in str(err):` I inserted:

    if not isinstance(err, str):
            raise ProtocolError(self, url, "{}".format(err.strerror))

At least I get some inkling on what's going on - in my case this bubbles up to my application from `requests` as:

 > requests.exceptions.ConnectionError: (<requests.packages.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f3999ba18d0>, '/', "[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]")

**Comment by jayvdb** [comment] 2015-07-15 14:46
@Lukasa , it looks like https://github.com/shazow/urllib3/commit/e2de9f67f276f5a9c2ca3689ce50eac2c7361f4f fixes this, or maybe it only fixes one aspect of this problem.

The cause is 2.7.9 introduced a new `SSLError.__str__` implementation that returns `strerror` , which means it must be a string.
https://hg.python.org/cpython/rev/92163#l23.297

The last release of urllib3, and requests, still has the problematic code
https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/contrib/pyopenssl.py#L290

I did a sync of pyopenssl.py only into requests, and it passed all tests.  But perhaps urllib3 is planning to release another version soon...?

**Comment by Lukasa** [comment] 2015-07-15 15:59
Requests has a policy about updating urllib3 releases, and part of it is that we do not force urllib3 to issue new releases. urllib3 will release when it's ready, and requests will release sometime after that. =)

**Comment by jayvdb** [comment] 2015-07-16 04:54
Appreciate that.  Is there any policy on urllib3 point releases, or any clues as to when urllib3 might be ready to release this fix?  Are there other issues that are 'must haves' for the next point release of urllib3?

urllib3 is busted on Python 2.7.9-10 if pyopenssl is installed - it fails whenever an invalid certificate is encountered, or other ssl errors.  fwiw this was introduced in the very first version (953b5a41) of pyopenssl support by @kirkeby, so there is no available version of urllib3 which can happily use pyopenssl on Python 2.7.9-10.

**Comment by Lukasa** [comment] 2015-07-16 06:20
I think urllib3 is likely to issue a point release fairly soon, if only because it's been a little while. That said, @shazow is the real authority here, I'm just the help. ;)

**Comment by shazow** [comment] 2015-07-16 10:32
Opened a milestone here, aiming for early next week for v1.11: https://github.com/shazow/urllib3/milestones/v1.11

**Comment by mcescalante** [comment] 2015-08-05 17:09
Thank you guys for your hard work so far on this problem :smile: . I'm still getting this error on a number of requests that I'm trying to make (via https), using Python 2.7.10 and urllib 1.11. Also tried a few past version of urllib.

It seems to still be at a state that @jayvdb described where there's no "safe" version of urllib3 that can be used with Python 2.7.9 or .10. I checked with Python 2.7.5 and I'm not getting the `TypeError: __str__ returned non-string (type SysCallError)` anymore. Just wondering, does anyone have any info on what's going on here?

**Comment by Lukasa** [comment] 2015-08-05 20:32
Requests 2.8.0 is imminent, but sadly right now I'm on holiday which means I have limited time available to make software releases. We *may* be able to get one out today, otherwise it'll hopefully be early next week: I'll co-ordinate with @sigmavirus24 to see if we can make that happen.

**Comment by mcescalante** [comment] 2015-08-05 20:44
@Lukasa and @sigmavirus24  don't worry / rush! I was just checking in on my beloved `requests` since I ran into this today while doing some https requests. Enjoy your holiday please! Thank you guys very much.

**Comment by lorenzog** [comment] 2015-10-08 09:53
Is this still happening with requests 2.8.0?

**Comment by borbamartin** [comment] 2016-01-25 16:23
Still happening on requests 2.9.1. Is there an ETA for this fix? Thanks!

**Comment by Lukasa** [comment] 2016-01-25 16:25
@borbamartin I do not believe this problem is still occurring on requests 2.9.1, because requests 2.9.1 contains urllib3 v1.13.1: this was fixed in urllib3 1.11. If you think you're suffering from a bug here, please open an issue on requests and we'll discuss further.

**Comment by Lukasa** [comment] 2016-01-25 16:26
Oh, I'm sorry, I don't know what I'm talking about: it's unclear that this has been fixed at all. Let me dig into it for a second.

**Comment by Lukasa** [comment] 2016-01-25 16:28
Though please note that this should have been at least partially fixed in urllib3 1.11. Can you please provide more details about what problem you're encountering, what version of requests you're using, where you got it from, and ideally some repro code?

**Comment by borbamartin** [comment] 2016-01-25 16:36
Lol, sure. I had to install requests[security] a couple of days ago to fix a handshake issue on a project, and now on another project which uses the same libraries I'm getting the error mentioned on this issue, and after uninstalling the security package and re-installing the regular requests package, it goes away.

I'm getting this when sending a simple GET request to a TLS 1.0 connection using TLS_RSA_WITH_RC4_128_MD5:
File ".../lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type SysCallError)

This are my packages:
requests (2.9.1)
pyOpenSSL (0.15.1)

Unfortunately I cannot provide a report code because it's a private server :(

Thanks in advance!

**Comment by borbamartin** [comment] 2016-01-25 16:37
You can get the same libraries (I assume are the latest ones) by 'pip install requests[security]'

**Comment by Lukasa** [comment] 2016-01-25 16:46
Hmm. Can you find line 185 of `requests/packages/urllib3/contrib/pyopenssl.py` and change it to read `raise SocketError(str(e))`?

**Comment by borbamartin** [comment] 2016-01-25 17:12
Changing that line returns a:
File ".../lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(54, 'ECONNRESET')",)

**Comment by Lukasa** [comment] 2016-01-25 17:13
Ok, that looks like the correct behaviour to me. Are you open to providing a patch for this (which will include writing a test, which may be tricky)? Or would you like to hold off and see if I can find time to do it.

**Comment by borbamartin** [comment] 2016-01-25 17:26
I'll have to hold off, this issue is still not solved for me, now I have to deal with the other error :( Thanks for your help @Lukasa !

**Comment by Lukasa** [comment] 2016-01-25 17:52
M'kay, see #792 for what should hopefully be the end of this surprisingly long-lived issue.

**Closed** 2016-01-25 19:58 UTC

**Comment by quecholac14** [comment] 2018-03-07 03:16
tenia el mismo problema mostraba error caba ves que entraba al admin y entraba a la base de dato me des lo sosucione canviando una letra de cada modelo  y usaba el manage.py makemigrations y el migrate  eso como que destrabo a django y lla caja yo tengo la version 1.11.4

**Comment by valerio-bozzolan** [comment] 2021-12-06 08:41
> I had to fix this on a production server by editing `requests/packages/urllib3/connectionpool.py`. At line 315, before `if 'timed out' in str(err) or 'did not complete (read)' in str(err):` I inserted:
> 
> ```
> if not isinstance(err, str) and hasattr(err, 'strerror'):
>         raise ProtocolError(self, url, "{}".format(err.strerror))
> ```
> 
> At least I get some inkling on what's going on - in my case this bubbles up to my application from `requests` as:
> 
> > requests.exceptions.ConnectionError: (<requests.packages.urllib3.connectionpool.HTTPSConnectionPool object at 0x7f3999ba18d0>, '/', "[('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]")

Just to say that this workaround was a good fix and that in Centos 7 that file is placed here:

```
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py
```

Moreover, the root cause of the `certificate verify failed` can be fixed updating your CA certificates. For example in Centos 7 you can update them using:

```
yum install ca-certificates
```
