### ISSUE TITLE
Cannot match IP hostnames in Python versions >= 3.2, < 3.5

### ISSUE THREAD

**Issue by paultiplady** [shazow/urllib3#921] opened 2016-07-09 20:33 UTC
Possibly related to https://github.com/shazow/urllib3/issues/258, but I'm not sure this is a dupe.

When using urllib3 to connect to https endpoints with certs signed for an IP address (instead of a hostname), urllib throws an error like this:

    SSLError: hostname '10.3.240.1' doesn't match either of 'kubernetes', 'kubernetes.default', 'kubernetes.default.svc', 'kubernetes.default.svc.cluster.local'

The problem appears to be that https://github.com/shazow/urllib3/blob/master/urllib3/packages/ssl_match_hostname/__init__.py uses the standard library implementation of `match_hostname` for Python versions >= 3.2, but that function only gained support for IP subjects in 3.5.

The fallback in that file is to use `backports.ssl_match_hostname`, which _does_ support IP subjects, as it backports 3.5's implementation.

Any chance we can fix urllib3 to use the backports version for Python versions < 3.5? Or perhaps just to preferentially take the backports version over the standard library version if backports is available? 

This issue is causing problems in downstream libraries, e.g. https://github.com/kelproject/pykube/issues/29, which can be resolved with monkey-patching, but the correct fix appears to be in urllib3.

**Comment by Lukasa** [comment] 2016-07-09 21:01
Hey @paultiplady! This is absolutely a dupe of the linked issue. I'm planning to take a look at this next week though!

**Closed by Lukasa** 2016-07-09 21:01 UTC

**Comment by paultiplady** [comment] 2016-07-09 22:00
Perfect, thanks Cory!
