### ISSUE TITLE
Urllib3 with h11 and trio

### ISSUE THREAD

**Issue by merrellb** [shazow/urllib3#1228] opened 2017-07-15 04:20 UTC
I've been following trio development these last few months and asynchronous HTTP requests are unsurprisingly high on my wish list.  @njsmith suggested urllib3 was probably the best way to robustly achieve this (https://github.com/python-trio/trio/issues/105).  I've noted that removing httplib has been closed (https://github.com/shazow/urllib3/pull/1067) and that the v2 branch hasn't been updated since May.   Does this mean we are close?  If not what additional work needs to be done?

**Comment by njsmith** [comment] 2017-07-15 04:44
#1067 was closed in favor of #1068, which is still open.

I've had some discussions with @Lukasa about this; my understanding is that he's dubious about providing pluggable network I/O in urllib3, but willing to discuss it. I don't think the v2 branch is abandoned, just that @Lukasa is a man with approximately 7 full-time jobs. And possibly part of the issue is that there's some unresolved questions around how to handle I/O, and if you look at how the v2 branch does I/O right now it's turned into a confusing mess, so some rethinking is needed, which in my experience of juggling way-too-many volunteer projects tends to drop things down the priority list...

My Secret Plan is to fix the v2 branch to support synchronous/trio/twisted backends, and then take it to @Lukasa like "hey look I made the synchronous I/O code work properly, so you don't have to give up on that, and also I made twisted work, which I know you've been wanting for a long time, and the code doesn't make your eyes bleed (and also I snuck trio support in)" and see if he finds that convincing :-). I actually have a half-finished branch here doing that that seems to be going well, but I deprioritized it a bit b/c I wanted to get happy eyeballs and [more robust SSLStream support](https://github.com/python-trio/trio/issues/198) landed in trio too, and unfortunately while my code is concurrent, I am serial and have a high context-switching overhead.

If you're interested in helping with the Secret Plan then that might change things a bit...

**Comment by Lukasa** [comment] 2017-07-15 06:34
Basically what @njsmith said. 😉

**Closed by Lukasa** 2017-07-15 06:34 UTC

**Comment by merrellb** [comment] 2017-07-16 06:54
I definitely would like to find a good way to contribute although your secret plan does sound rather ambitious (especially if it has already proven difficult for @Lukasa!).  Is your branch publicly available?  I would certainly be happy to take a look and see if it is something that could be in my wheelhouse (although with no twisted experience it may be a bridge too far)

**Comment by njsmith** [comment] 2017-07-28 07:05
I found a chance to poke at my branch a bit more, pushed it to my fork, and wrote some notes here so we don't keep cluttering up the urllib3 notifications with this wacky experiment: https://github.com/njsmith/urllib3/issues/1

It's definitely in a state where it could do with some relatively mechanical assistance – certainly there's plenty to do without touching twisted code :-).
